### ISSUE TITLE
One space in a param makes scriptrun fail

### ISSUE THREAD

**Issue by k9ert** [hybris/zenboot#84]
If you have a param which is simply one space (" ") then zenboot fails with this exception 

`
zenboot_1 | 2016-09-27 15:39:38,713 [http-nio-8080-exec-4] INFO  processing.ExecutionZoneController  - cmd setParameters:['scriptDir':'/home/user/zenboot/zenboot-scripts/docker-misc/scripts/spin_up_dockerenabled', 'parameters.key':['BOX_NAME', 'CUSTOMER_EMAIL', 'ANSIBLE_ADDITIONAL_OPTS', 'COMPOSE_SCRIPTS_CLONE_DIR', 'COMPOSE_SCRIPTS_REPO', 'DATACENTER', 'DOMAIN', 'ENV_ROLE', 'ONSSHKEY', 'ONSSHUSER', 'ON_WRAPPER', 'OPENNEBULA', 'ROT_ON_USERNAME', 'SECURE_CORNER_BASE', 'START_OPTS', 'STATSD_HOST', 'SUBDOMAIN', 'TEMPLATEID'], 'parameters':['key':['BOX_NAME', 'CUSTOMER_EMAIL', 'ANSIBLE_ADDITIONAL_OPTS', 'COMPOSE_SCRIPTS_CLONE_DIR', 'COMPOSE_SCRIPTS_REPO', 'DATACENTER', 'DOMAIN', 'ENV_ROLE', 'ONSSHKEY', 'ONSSHUSER', 'ON_WRAPPER', 'OPENNEBULA', 'ROT_ON_USERNAME', 'SECURE_CORNER_BASE', 'START_OPTS', 'STATSD_HOST', 'SUBDOMAIN', 'TEMPLATEID'], 'value':['kimsbox', 'kim.neunert@sap.com', '-v', '/var/tmp/docker-compose-repo', 'ssh://git@enterprise-stash.hybris.com:7999/is/pd-docker.git', 'rot', 'kimtest.cis.b2c.ydev.hybris.com', '.', '../../../../secure-corner/kim_opennebula_id_rsa', 'kimneunert', 'default', 'onepod1a.system.fra.hybris.com', 'aod', '../../../../secure-corner', ' ', 'statsd.rpi.ydev.hybris.com', 'yrdci', '318']], 'parameters.value':['kimsbox', 'kim.neunert@sap.com', '-v', '/var/tmp/docker-compose-repo', 'ssh://git@enterprise-stash.hybris.com:7999/is/pd-docker.git', 'rot', 'kimtest.cis.b2c.ydev.hybris.com', '.', '../../../../secure-corner/kim_opennebula_id_rsa', 'kimneunert', 'default', 'onepod1a.system.fra.hybris.com', 'aod', '../../../../secure-corner', ' ', 'statsd.rpi.ydev.hybris.com', 'yrdci', '318'], 'containsInvisibleParameters':'false', 'execId':'183', 'comment':'', '_action_execute':'Execute', 'controller':'executionZone', 'format':null, 'action':'index']

zenboot_1 | 2016-09-27 15:39:38,832 [http-nio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - TransientObjectException occurred when processing request: [POST] /zenboot/executionZone/index

zenboot_1 | object references an unsaved transient instance - save the transient instance before flushing: org.zenboot.portal.processing.ProcessingParameter. Stacktrace follows:

zenboot_1 | org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: org.zenboot.portal.processing.ProcessingParameter

zenboot_1 | 	at org.zenboot.portal.processing.ExecutionZoneService.createExecutionZoneAction(ExecutionZoneService.groovy:182)

zenboot_1 | 	at org.zenboot.portal.processing.ExecutionZoneService.createExecutionZoneAction(ExecutionZoneService.groovy:157)

zenboot_1 | 	at org.zenboot.portal.processing.ExecuteExecutionZoneCommand.getExecutionZoneAction(ExecutionZoneController.groovy:407)

zenboot_1 | 	at org.zenboot.portal.processing.ExecutionZoneController.execute(ExecutionZoneController.groovy:53)

zenboot_1 | 	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)

zenboot_1 | 	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)

zenboot_1 | 	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.java:59)

zenboot_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

zenboot_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

zenboot_1 | 	at java.lang.Thread.run(Thread.java:745)

`

**Comment by mstadelm** [comment]
I created a new branch bugfix/issue84. The commit:

https://github.com/hybris/zenboot/commit/20cc37fcaee5d1a2abd294e777a303f68386bc9e

Works fine on my local machine.
